### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by mithun** [jfrog/bower-art-resolver#11]
The resolver does not recognize and pass-thru [1] the SSL certificate configurations [2] from .bowerrc. This is a major blocker when Artifactory is served via HTTPS using self-signed certificates.

I can currently work around this by setting "ssl-strict" to false, but I would rather not do that.

[1] https://github.com/JFrogDev/bower-art-resolver/blob/master/lib/request.js#L12
[2] https://github.com/bower/spec/blob/master/config.md#ca

**Comment by jblaine** [comment]
It is a major blocker too when Artifactory is served via HTTPS using certificates signed by an internal enterprise CA as well.

**Comment by jgibson** [comment]
First of all, for a complete fix you'll also have to update [download.js](https://github.com/JFrogDev/bower-art-resolver/blob/master/lib/download.js#L41).

I just fixed this locally in a hackish way by using `config.ca.search[0]`.  However, a proper implementation requires a fix in bower itself. The other resolvers (ex. [GitHub](https://github.com/bower/bower/blob/ce15df27ca728349799b3c6a2db1a5f1e9b4e9e8/lib/core/resolvers/GitHubResolver.js#L75), [Url](https://github.com/bower/bower/blob/ce15df27ca728349799b3c6a2db1a5f1e9b4e9e8/lib/core/resolvers/UrlResolver.js#L58)) use the `ca.default` configuration option, and the Artifactory resolver probably should too. Unfortunately the `ca.default` option doesn't support reading multiple CA certificates from a file: bower/config#33. Once that issue is resolved then the fix is pretty straight-forward.

**Comment by eyalbe4** [comment]
@jgibson, can you please share your fix? Do you think it can be merged to the Artifactory resolver code to fix the issue?

**Comment by jgibson** [comment]
While we could merge my fix it probably would not work properly for anyone who [uses multiple registries](https://github.com/bower/spec/blob/master/config.md#registrysearch). Once bower/config#33 is fixed that would let us resolve the issue correctly.

Also, I would need to get approval from my employer to sign the [Contributor License Agreement](https://www.jfrog.com/confluence/display/OSS/How+to+Contribute).
